Name:           ros-melodic-catkin-virtualenv
Version:        0.5.0
Release:        2%{?dist}
Summary:        ROS catkin_virtualenv package

Group:          Development/Libraries
License:        GPL
Source0:        %{name}-%{version}.tar.gz

Requires:       python-enum34
Requires:       python-packaging
Requires:       python-virtualenv
Requires:       python3-devel
Requires:       python3-libs
Requires:       ros-melodic-rosbash
Requires:       virtualenv
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslint

%description
Bundle python requirements in a catkin package via virtualenv.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Sep 16 2019 Paul Bovbel <pbovbel@locusrobotics.com> - 0.5.0-2
- Autogenerated by Bloom

* Fri Aug 30 2019 Paul Bovbel <pbovbel@locusrobotics.com> - 0.5.0-1
- Autogenerated by Bloom

* Tue Jun 11 2019 Paul Bovbel <pbovbel@locusrobotics.com> - 0.4.1-1
- Autogenerated by Bloom

* Mon Mar 18 2019 Paul Bovbel <pbovbel@locusrobotics.com> - 0.4.0-0
- Autogenerated by Bloom

